import type { Metadata } from "next";
import { Inter, Noto_Sans_Thai, Monoton } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navigation/navbar";

const inter = Inter({ subsets: ["latin"] });
const notoSansThai = Noto_Sans_Thai({ subsets: ["thai", "latin"] });
const monoton = Monoton({ subsets: ["latin"], weight: "400" }); // Add Monoton

export const metadata: Metadata = {
  title: "Memory of Baan Poon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${notoSansThai.className} pt-20 min-h-screen bg-[#efeeeb]`}
      >
        <Navbar monotonClass={monoton.className} />
        {/* Pass the class as a prop */}
        {children}
      </body>
    </html>
  );
}
